### ISSUE TITLE
after timeout, my server becomes unreachable.

### ISSUE THREAD

**Issue by zhaohanweng** [ankane/slowpoke#5]
I am running local puma server, allowing 1 query at a time, and set the `Slowpoke.timeout = 1` in the initializer.

After my first query received timeout error. my app just logs this.. and all my other query just fails with `net::ERR_ADDRESS_UNREACHABLE`

LOG:
...
```
Exiting
2015-08-27 15:39:31 -0400: Rack app error: #<ThreadError: Attempt to unlock a mutex which is locked by another thread>2015-08-27 15:39:31 -0400: Rack app error: #<ThreadError: Attempt to unlock a mutex which is locked by another thread>
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:22:in `unlock'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:22:in `ensure in call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:23:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/static.rb:84:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slowpoke-0.1.1/lib/slowpoke/middleware.rb:8:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.1.12/lib/rails/engine.rb:514:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.1.12/lib/rails/application.rb:144:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:541:in `handle_request'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:388:in `process_client'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:270:in `block in run'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `block in spawn_thread'2015-08-27 15:39:31 -0400: Rack app error: #<ThreadError: Attempt to unlock a mutex which is locked by another thread>
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:22:in `unlock'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:22:in `ensure in call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:23:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/static.rb:84:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67
:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slowpoke-0.1.1/lib/slowpoke/middleware.rb:8:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.1.12/lib/rails/engine.rb:514:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.1.12/lib/rails/application.rb:144:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:541:in `handle_request'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:388:in `process_client'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:270:in `block in run'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `block in spawn_thread'2015-08-27 15:39:31 -0400: Rack app error: #<ThreadError: Attempt to unlock a mutex which is locked by another thread>2015-08-27 15:39:31 -0400: Rack app error: #<ThreadError: Attempt to unlock a mutex which is locked by another thread>
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:22:in `unlock'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:22:in `ensure in call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:23:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/static.rb:84:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slowpoke-0.1.1/lib/slowpoke/middleware.rb:8:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.1.12/lib/rails/engine.rb:514:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.1.12/lib/rails/application.rb:144:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:541:in `handle_request'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:388:in `process_client'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:270:in `block in run'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `block in spawn_thread'/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:22:in `unlock'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:22:in `ensure in call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:23:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/static.rb:84:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:i
n `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slowpoke-0.1.1/lib/slowpoke/middleware.rb:8:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.1.12/lib/rails/engine.rb:514:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.1.12/lib/rails/application.rb:144:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:541:in `handle_request'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:388:in `process_client'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:270:in `block in run'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `block in spawn_thread'


/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:22:in `unlock'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:22:in `ensure in call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/lock.rb:23:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.1.12/lib/action_dispatch/middleware/static.rb:84:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slowpoke-0.1.1/lib/slowpoke/middleware.rb:8:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.1.12/lib/rails/engine.rb:514:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.1.12/lib/rails/application.rb:144:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:541:in `handle_request'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:388:in `process_client'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:270:in `block in run'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `block in spawn_thread'

2015-08-27 15:39:31 -0400: Read error: #<IOError: closed stream>
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `write'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `<<'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `block in add'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:165:in `synchronize'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:165:in `add'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:401:in `process_client'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:270:in `block in run'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
2015-08-27 15:39:31 -0400: Read error: #<IOError: closed stream>
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `write'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `<<'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `block in add'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:165:in `synchronize'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:165:in `add'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:401:in `process_client'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:270:in `block in run'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `2015-08-27 15:39:31 -0400: Read error: #<IOError: closed stream>
call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `block in spawn_thread'2015-08-27 15:39:31 -0400: Read error: #<IOError: closed stream>/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `write'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `<<'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `block in add'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:165:in `synchronize'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:165:in `add'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:401:in `process_client'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:270:in `block in run'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `block in spawn_thread'2015-08-27 15:39:31 -0400: Read error: #<IOError: closed stream>


/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `write'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `<<'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `block in add'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:165:in `synchronize'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:165:in `add'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:401:in `process_client'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:270:in `block in run'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `block in spawn_thread'

/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `write'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `<<'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:167:in `block in add'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:165:in `synchronize'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/reactor.rb:165:in `add'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:401:in `process_client'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:270:in `block in run'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by ankane** [comment]
Hey @zhaohanweng, are you still seeing this with the latest version of Puma?

**Comment by zhaohanweng** [comment]
Sorry, I am no longer working on the project.

**Comment by ankane** [comment]
No worries, I'll mark this and #6 as closed.
